import type { Metadata } from "next";
import "./globals.css";

import Navigation from "./components/navigation";
import React from 'react'

import {FaFacebookF} from "react-icons/fa"
import {FiInstagram} from "react-icons/fi"
import {IoLogoTwitter} from "react-icons/io"

export const metadata: Metadata = {
  title: "Andrew Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation />

        {children}

    <footer className='bg-[#050C17] text-center py-12 px-0 mt-[7rem] flex flex-col justify-center items-center gap-5'>
      <a href="#" className=''>ANDREW</a>
      <ul className="flex gap-[2rem] flex-col lg:flex-row justify-center flex-wrap ">
        <li><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#skills">Skills</a></li>
        <li><a href="#projects">Projects</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
      <div className="flex gap-[2rem] justify-center btn btn-primary-outline">
        <a href="https://facebook.com"><FaFacebookF /></a>
        <a href="https://instagram.com"><FiInstagram /></a>
        <a href="https://twitter.com"><IoLogoTwitter /></a>
      </div>
      <div className="">
        <small>Adetokunbo Andrew. All rights reserved.</small>
      </div>
    </footer>
      </body>
    </html>
  );
}
